spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true

logging:
  level:
    org.hibernate.type: TRACE
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG

